sudo: required
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run test-e2e-ci
- npm run build-ci
before_deploy:
  - cd dist/deividfortuna/input-number
deploy:
  provider: npm
  email: deividfortuna@gmail.com
  skip_cleanup: true
  api_key: $NPM_KEY
  on:
    tags: true
    repo: deividfortuna/ngx-input-number