name: Npm Release

# on tag push
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.com'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-ci

      - name: Release
        run: |
          npm config set registry https://registry.npmjs.com
          npm publish --access public
        working-directory: dist/deividfortuna/input-number
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}